language: generic

cache:
  apt: true

addons:
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.8

matrix:
  include:
    - env: CC=gcc-6 CXX=g++-6
      os: linux
      dist: trusty
      sudo: require
      addons:
        apt:
          sources: *sources
          packages:
            - gcc-6
            - g++-6

    - env: CC=gcc-5 CXX=g++-5
      os: linux
      dist: trusty
      sudo: require
      addons:
        apt:
          sources: *sources
          packages:
            - gcc-5
            - g++-5

    - env: CC=clang-3.8 CXX=clang++-3.8
      os: linux
      dist: trusty
      sudo: require
      addons:
        apt:
          sources: *sources
          packages:
            - g++-6 # Hack to make clang work.
            - clang-3.8

    - env: CC=clang-3.6 CXX=clang++-3.6
      os: linux
      dist: trusty
      sudo: require
      addons:
        apt:
          sources: *sources
          packages:
            - clang-3.6

    - os: osx
      osx_image: xcode8.2
      before_install:
        - brew update
        - brew install --overwrite cmake

script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build . --config debug
    - ctest -V -C debug
